# Generated by Django 4.2 on 2023-04-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='beautiful-mountain-view.png', null=True, upload_to='images/'),
        ),
    ]
