# Generated by Django 4.2 on 2023-04-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='beautiful-mountain-view.png', null=True, upload_to='images/', verbose_name='Load Image'),
        ),
    ]
